/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.app.App

import org.example.app.Fecha

fun main() {
    val fecha: Fecha = Fecha(29, 5, 2026)
    println(App().greeting)
    println(fecha.toString())
}
